// <auto-generated />
using System;
using Crud.App.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Crud.App.Infra.Data.Migrations
{
    [DbContext(typeof(CrudAppContext))]
    partial class CrudAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Crud.App.Domain.Usuarios.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Crud.App.Domain.Usuarios.Usuario", b =>
                {
                    b.OwnsOne("Crud.App.Domain.Usuarios.ValueObjects.NomeCompleto", "NomeCompleto", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId");

                            b1.Property<string>("PrimeiroNome")
                                .IsRequired()
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("SegundoNome")
                                .IsRequired()
                                .HasColumnType("varchar(50)");

                            b1.Property<string>("UltimoNome")
                                .HasColumnType("varchar(50)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.HasOne("Crud.App.Domain.Usuarios.Usuario")
                                .WithOne("NomeCompleto")
                                .HasForeignKey("Crud.App.Domain.Usuarios.ValueObjects.NomeCompleto", "UsuarioId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });

                    b.OwnsOne("Crud.App.Domain.Usuarios.ValueObjects.Telefone", "Telefone", b1 =>
                        {
                            b1.Property<Guid>("UsuarioId");

                            b1.Property<string>("DDD")
                                .IsRequired()
                                .HasColumnType("varchar(02)");

                            b1.Property<string>("Numero")
                                .IsRequired()
                                .HasColumnType("varchar(09)");

                            b1.HasKey("UsuarioId");

                            b1.ToTable("Usuario");

                            b1.HasOne("Crud.App.Domain.Usuarios.Usuario")
                                .WithOne("Telefone")
                                .HasForeignKey("Crud.App.Domain.Usuarios.ValueObjects.Telefone", "UsuarioId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
